import type { Circuit, PlacedGate } from "../editor/types";

/**
 * Emit a PyQuil program from a Circuit IR. Targets Rigetti's `Program`
 * built from `pyquil.gates`. Free parameters become `Parameter` declarations.
 */

const GLYPH_TO_ASCII: Array<[string, string]> = [
  ["π", "pi"], ["θ", "theta"], ["φ", "phi"], ["λ", "lambda"],
  ["γ", "gamma"], ["β", "beta"], ["τ", "tau"], ["α", "alpha"],
  ["δ", "delta"], ["ω", "omega"],
];
const FREE_SYMBOL_NAMES = ["theta", "phi", "lambda", "gamma", "beta", "tau", "alpha", "delta", "omega"];

function asciify(s: string): string {
  let o = s;
  for (const [g, a] of GLYPH_TO_ASCII) o = o.split(g).join(a);
  return o.trim();
}

function emitGate(g: PlacedGate): string[] {
  const t = g.targets[0];
  const t1 = g.targets[1];
  const c0 = g.controls[0];

  if (g.gateId === "barrier") return [`# barrier — PyQuil has no explicit barrier op`];
  if (g.gateId === "measure") return [`p += MEASURE(${t}, ro[${g.clbits[0]}])`];
  if (g.gateId === "reset") return [`p += RESET(${t})`];

  if (g.gateId === "init0") return [`p += RESET(${t})`];
  if (g.gateId === "init1") return [`p += RESET(${t})`, `p += X(${t})`];
  if (g.gateId === "initplus") return [`p += RESET(${t})`, `p += H(${t})`];

  switch (g.gateId) {
    case "i": return [`p += I(${t})`];
    case "x": return [`p += X(${t})`];
    case "y": return [`p += Y(${t})`];
    case "z": return [`p += Z(${t})`];
    case "h": return [`p += H(${t})`];
    case "s": return [`p += S(${t})`];
    case "sdg": return [`p += S(${t}).dagger()`];
    case "t": return [`p += T(${t})`];
    case "tdg": return [`p += T(${t}).dagger()`];
  }

  if (g.gateId === "rx") return [`p += RX(${asciify(g.params[0])}, ${t})`];
  if (g.gateId === "ry") return [`p += RY(${asciify(g.params[0])}, ${t})`];
  if (g.gateId === "rz") return [`p += RZ(${asciify(g.params[0])}, ${t})`];
  if (g.gateId === "p" || g.gateId === "u1") return [`p += PHASE(${asciify(g.params[0])}, ${t})`];

  if (g.gateId === "cx") return [`p += CNOT(${c0}, ${t})`];
  if (g.gateId === "cz") return [`p += CZ(${c0}, ${t})`];
  if (g.gateId === "swap") return [`p += SWAP(${t}, ${t1})`];
  if (g.gateId === "iswap") return [`p += ISWAP(${t}, ${t1})`];
  if (g.gateId === "ccx") return [`p += CCNOT(${g.controls[0]}, ${g.controls[1]}, ${t})`];
  if (g.gateId === "cswap") return [`p += CSWAP(${c0}, ${t}, ${t1})`];

  if (g.gateId === "rxx") return [`p += XY(${asciify(g.params[0])}, ${t}, ${t1})  # approximation`];

  return [`# ${g.gateId}: no direct PyQuil mapping`];
}

function collectSymbols(circuit: Circuit): string[] {
  const found = new Set<string>();
  for (const g of circuit.gates) {
    for (const raw of g.params) {
      const t = asciify(raw);
      for (const n of FREE_SYMBOL_NAMES) {
        const re = new RegExp(`(^|[^A-Za-z0-9_])${n}([^A-Za-z0-9_]|$)`);
        if (re.test(t)) found.add(n);
      }
    }
  }
  return [...found].sort();
}

export function emitPyQuil(circuit: Circuit): string {
  const out: string[] = [];
  out.push("# Generated by Quantiom — PyQuil export");
  out.push("from pyquil import Program");
  out.push("from pyquil.gates import H, X, Y, Z, S, T, I, RX, RY, RZ, PHASE, CNOT, CZ, SWAP, ISWAP, CCNOT, CSWAP, MEASURE, RESET, XY");
  out.push("from pyquil.quil import Parameter");
  const symbols = collectSymbols(circuit);
  if (symbols.length > 0) out.push("from math import pi");
  out.push("");
  for (const s of symbols) out.push(`${s} = Parameter("${s}")`);
  if (symbols.length > 0) out.push("");
  out.push("p = Program()");
  if (circuit.numClbits > 0) out.push(`ro = p.declare("ro", "BIT", ${circuit.numClbits})`);
  out.push("");
  const sorted = [...circuit.gates].sort((a, b) => a.column - b.column || a.id.localeCompare(b.id));
  for (const g of sorted) for (const line of emitGate(g)) out.push(line);
  out.push("");
  out.push("# print(p)");
  return out.join("\n");
}
