import type { Circuit, PlacedGate } from "../editor/types";

/**
 * Emit a Q# program from a Circuit IR.
 *
 * Targets a single `operation Main() : Result[]` that allocates the
 * qubit register, applies the gates from Microsoft.Quantum.Intrinsic
 * and Microsoft.Quantum.Canon, and returns the measurement results.
 */

const GLYPH_TO_ASCII: Array<[string, string]> = [
  ["π", "PI()"], ["θ", "theta"], ["φ", "phi"], ["λ", "lambda_"],
  ["γ", "gamma"], ["β", "beta"], ["τ", "tau"], ["α", "alpha"],
  ["δ", "delta"], ["ω", "omega"],
];
const FREE_SYMBOL_NAMES = ["theta", "phi", "lambda_", "gamma", "beta", "tau", "alpha", "delta", "omega"];

function asciify(s: string): string {
  let o = s;
  for (const [g, a] of GLYPH_TO_ASCII) o = o.split(g).join(a);
  // Q# uses Microsoft.Quantum.Math.PI(); convert literal `pi` too.
  o = o.replace(/\bpi\b/g, "PI()");
  return o.trim();
}

function emitGate(g: PlacedGate): string[] {
  const t = g.targets[0];
  const t1 = g.targets[1];
  const c0 = g.controls[0];

  if (g.gateId === "barrier") return [`// barrier`];
  if (g.gateId === "delay") return [`// delay(${asciify(g.params[0] ?? "0")})`];

  if (g.gateId === "measure") return [`set results w/= ${g.clbits[0]} <- M(qs[${t}]);`];
  if (g.gateId === "measure_x") return [
    `H(qs[${t}]);`,
    `set results w/= ${g.clbits[0]} <- M(qs[${t}]);`,
    `H(qs[${t}]);`,
  ];
  if (g.gateId === "measure_y") return [
    `Adjoint S(qs[${t}]);`,
    `H(qs[${t}]);`,
    `set results w/= ${g.clbits[0]} <- M(qs[${t}]);`,
    `H(qs[${t}]);`,
    `S(qs[${t}]);`,
  ];
  if (g.gateId === "reset") return [`Reset(qs[${t}]);`];

  if (g.gateId === "init0") return [`Reset(qs[${t}]);`];
  if (g.gateId === "init1") return [`Reset(qs[${t}]);`, `X(qs[${t}]);`];
  if (g.gateId === "initplus") return [`Reset(qs[${t}]);`, `H(qs[${t}]);`];
  if (g.gateId === "initminus") return [`Reset(qs[${t}]);`, `X(qs[${t}]);`, `H(qs[${t}]);`];
  if (g.gateId === "initiplus") return [`Reset(qs[${t}]);`, `H(qs[${t}]);`, `S(qs[${t}]);`];
  if (g.gateId === "initiminus") return [`Reset(qs[${t}]);`, `H(qs[${t}]);`, `Adjoint S(qs[${t}]);`];

  switch (g.gateId) {
    case "i": return [`I(qs[${t}]);`];
    case "x": return [`X(qs[${t}]);`];
    case "y": return [`Y(qs[${t}]);`];
    case "z": return [`Z(qs[${t}]);`];
    case "h": return [`H(qs[${t}]);`];
    case "s": return [`S(qs[${t}]);`];
    case "sdg": return [`Adjoint S(qs[${t}]);`];
    case "t": return [`T(qs[${t}]);`];
    case "tdg": return [`Adjoint T(qs[${t}]);`];
    case "sx": return [`Rx(PI()/2.0, qs[${t}]);`, `// √X via Rx(π/2) up to a global phase`];
    case "sxdg": return [`Rx(-PI()/2.0, qs[${t}]);`];
  }

  if (g.gateId === "rx") return [`Rx(${asciify(g.params[0])}, qs[${t}]);`];
  if (g.gateId === "ry") return [`Ry(${asciify(g.params[0])}, qs[${t}]);`];
  if (g.gateId === "rz") return [`Rz(${asciify(g.params[0])}, qs[${t}]);`];
  if (g.gateId === "p" || g.gateId === "u1") return [`R1(${asciify(g.params[0])}, qs[${t}]);`];

  if (g.gateId === "u" || g.gateId === "u3") {
    const [th, ph, la] = g.params.map(asciify);
    return [
      `// U(θ,φ,λ): Rz(λ) Ry(θ) Rz(φ)`,
      `Rz(${la}, qs[${t}]);`,
      `Ry(${th}, qs[${t}]);`,
      `Rz(${ph}, qs[${t}]);`,
    ];
  }

  if (g.gateId === "cx") return [`CNOT(qs[${c0}], qs[${t}]);`];
  if (g.gateId === "cz") return [`CZ(qs[${c0}], qs[${t}]);`];
  if (g.gateId === "cy") return [`Controlled Y([qs[${c0}]], qs[${t}]);`];
  if (g.gateId === "ch") return [`Controlled H([qs[${c0}]], qs[${t}]);`];
  if (g.gateId === "swap") return [`SWAP(qs[${t}], qs[${t1}]);`];

  if (g.gateId === "rxx") return [`Rxx(${asciify(g.params[0])}, qs[${t}], qs[${t1}]);`];
  if (g.gateId === "ryy") return [`Ryy(${asciify(g.params[0])}, qs[${t}], qs[${t1}]);`];
  if (g.gateId === "rzz") return [`Rzz(${asciify(g.params[0])}, qs[${t}], qs[${t1}]);`];

  if (g.gateId === "ccx") return [`CCNOT(qs[${g.controls[0]}], qs[${g.controls[1]}], qs[${t}]);`];
  if (g.gateId === "cswap") return [`Controlled SWAP([qs[${g.controls[0]}]], (qs[${g.targets[0]}], qs[${g.targets[1]}]));`];

  if (g.gateId === "mcx") {
    const ctrls = g.controls.map((c) => `qs[${c}]`).join(", ");
    return [`Controlled X([${ctrls}], qs[${t}]);`];
  }

  return [`// ${g.gateId}: no direct Q# mapping in this emitter`];
}

function collectSymbols(circuit: Circuit): string[] {
  const found = new Set<string>();
  for (const g of circuit.gates) {
    for (const raw of g.params) {
      const t = asciify(raw);
      for (const n of FREE_SYMBOL_NAMES) {
        const re = new RegExp(`(^|[^A-Za-z0-9_])${n}([^A-Za-z0-9_]|$)`);
        if (re.test(t)) found.add(n);
      }
    }
  }
  return [...found].sort();
}

export function emitQSharp(circuit: Circuit): string {
  const out: string[] = [];
  out.push("// Generated by Quantiom — Q# export");
  out.push("open Microsoft.Quantum.Intrinsic;");
  out.push("open Microsoft.Quantum.Canon;");
  out.push("open Microsoft.Quantum.Math;");
  out.push("");
  const symbols = collectSymbols(circuit);
  const params = symbols.length > 0 ? symbols.map((s) => `${s} : Double`).join(", ") : "";
  out.push(`operation Main(${params}) : Result[] {`);
  out.push(`    use qs = Qubit[${circuit.numQubits}];`);
  out.push(`    mutable results = [Zero, size = ${Math.max(1, circuit.numClbits)}];`);
  const sorted = [...circuit.gates].sort((a, b) => a.column - b.column || a.id.localeCompare(b.id));
  for (const g of sorted) {
    for (const line of emitGate(g)) out.push(`    ${line}`);
  }
  out.push(`    ResetAll(qs);`);
  out.push(`    return results;`);
  out.push(`}`);
  return out.join("\n");
}
