import type { Circuit, PlacedGate } from "../editor/types";
import { exportLower } from "./exportLower";

/**
 * Emit a pytket (Quantinuum) Python program from a Circuit IR. Targets
 * `pytket.Circuit` with method-style gate calls.
 */

const GLYPH_TO_ASCII: Array<[string, string]> = [
  ["π", "pi"], ["θ", "theta"], ["φ", "phi"], ["λ", "lambda"],
  ["γ", "gamma"], ["β", "beta"], ["τ", "tau"], ["α", "alpha"],
  ["δ", "delta"], ["ω", "omega"],
];
const FREE_SYMBOL_NAMES = ["theta", "phi", "lambda", "gamma", "beta", "tau", "alpha", "delta", "omega"];

function asciify(s: string): string {
  let o = s;
  for (const [g, a] of GLYPH_TO_ASCII) o = o.split(g).join(a);
  return o.trim();
}

/** pytket measures angles in units of half-turns (1 turn = 2π). */
function piParts(expr: string): string {
  return `(${expr}) / pi`;
}

function emitGate(g: PlacedGate): string[] {
  const lowered = exportLower(g);
  if (lowered) return lowered.flatMap(emitGate);
  const t = g.targets[0];
  const t1 = g.targets[1];
  const c0 = g.controls[0];

  if (g.gateId === "barrier") return [`c.add_barrier([${g.targets.join(", ")}])`];
  if (g.gateId === "measure") return [`c.Measure(${t}, ${g.clbits[0]})`];
  if (g.gateId === "reset") return [`c.Reset(${t})`];

  switch (g.gateId) {
    case "i": return [`c.add_gate(OpType.noop, [${t}])`];
    case "x": return [`c.X(${t})`];
    case "y": return [`c.Y(${t})`];
    case "z": return [`c.Z(${t})`];
    case "h": return [`c.H(${t})`];
    case "s": return [`c.S(${t})`];
    case "sdg": return [`c.Sdg(${t})`];
    case "t": return [`c.T(${t})`];
    case "tdg": return [`c.Tdg(${t})`];
    case "sx": return [`c.SX(${t})`];
    case "sxdg": return [`c.SXdg(${t})`];
  }

  if (g.gateId === "rx") return [`c.Rx(${piParts(asciify(g.params[0]))}, ${t})`];
  if (g.gateId === "ry") return [`c.Ry(${piParts(asciify(g.params[0]))}, ${t})`];
  if (g.gateId === "rz") return [`c.Rz(${piParts(asciify(g.params[0]))}, ${t})`];

  if (g.gateId === "cx") return [`c.CX(${c0}, ${t})`];
  if (g.gateId === "cz") return [`c.CZ(${c0}, ${t})`];
  if (g.gateId === "cy") return [`c.CY(${c0}, ${t})`];
  if (g.gateId === "ch") return [`c.CH(${c0}, ${t})`];
  if (g.gateId === "swap") return [`c.SWAP(${t}, ${t1})`];
  if (g.gateId === "ccx") return [`c.CCX(${g.controls[0]}, ${g.controls[1]}, ${t})`];
  if (g.gateId === "cswap") return [`c.CSWAP(${c0}, ${t}, ${t1})`];

  if (g.gateId === "rxx") return [`c.XXPhase(${piParts(asciify(g.params[0]))}, ${t}, ${t1})`];
  if (g.gateId === "ryy") return [`c.YYPhase(${piParts(asciify(g.params[0]))}, ${t}, ${t1})`];
  if (g.gateId === "rzz") return [`c.ZZPhase(${piParts(asciify(g.params[0]))}, ${t}, ${t1})`];

  return [`# ${g.gateId}: no direct pytket mapping`];
}

function collectSymbols(circuit: Circuit): string[] {
  const found = new Set<string>();
  for (const g of circuit.gates) {
    for (const raw of g.params) {
      const t = asciify(raw);
      for (const n of FREE_SYMBOL_NAMES) {
        const re = new RegExp(`(^|[^A-Za-z0-9_])${n}([^A-Za-z0-9_]|$)`);
        if (re.test(t)) found.add(n);
      }
    }
  }
  return [...found].sort();
}

export function emitPytket(circuit: Circuit): string {
  const out: string[] = [];
  out.push("# Generated by Quantiom — pytket export");
  out.push("from pytket import Circuit, OpType");
  out.push("from sympy import Symbol, pi");
  out.push("");
  const symbols = collectSymbols(circuit);
  for (const s of symbols) out.push(`${s} = Symbol("${s}")`);
  if (symbols.length > 0) out.push("");
  if (circuit.numClbits > 0) {
    out.push(`c = Circuit(${circuit.numQubits}, ${circuit.numClbits})`);
  } else {
    out.push(`c = Circuit(${circuit.numQubits})`);
  }
  out.push("");
  out.push("# Note: pytket measures rotations in half-turns (1 turn = 2π).");
  out.push("# Angles below are divided by π so the source numbers match Quantiom's.");
  out.push("");
  const sorted = [...circuit.gates].sort((a, b) => a.column - b.column || a.id.localeCompare(b.id));
  for (const g of sorted) for (const line of emitGate(g)) out.push(line);
  out.push("");
  out.push("# print(c)");
  return out.join("\n");
}
