import type { Circuit, PlacedGate } from "../editor/types";
import { newGateId } from "../editor/state";

/**
 * Rewrite a circuit into a chosen target gate set.
 *
 * Target sets implemented:
 *   • "clifford-t" — {H, S, S†, T, T†, CX}. The standard fault-tolerance
 *     basis. RZ/RY/RX with non-Clifford-T angles cannot be exactly
 *     represented and are left as-is with a warning (Solovay-Kitaev /
 *     Ross-Selinger approximation is a research-grade problem that
 *     warrants its own session).
 *   • "ibm-heavy-hex" — {RZ, SX, CX}. The IBM device native set.
 *     H / S / X / Y / Z / T / RX / RY / U / U3 all decompose into
 *     RZ·SX combinations.
 *   • "rigetti" — {RZ, RX(±π/2), CZ}. Rigetti device native set.
 *
 * Decompositions are local — each gate translates independently and the
 * column scheduler is regenerated by ASAP packing. The result is a fresh
 * circuit with the same numQubits / numClbits.
 */

export type TranspileTarget = "clifford-t" | "ibm-heavy-hex" | "rigetti";

export type TranspileResult = {
  circuit: Circuit;
  before: { gates: number; cx: number; tCount: number; depth: number };
  after: { gates: number; cx: number; tCount: number; depth: number };
  skipped: Array<{ gateId: string; reason: string }>;
};

export function transpile(circuit: Circuit, target: TranspileTarget): TranspileResult {
  const before = countMetrics(circuit.gates);
  const skipped: Array<{ gateId: string; reason: string }> = [];
  const out: PlacedGate[] = [];
  const sorted = [...circuit.gates].sort((a, b) => a.column - b.column || a.id.localeCompare(b.id));

  for (const g of sorted) {
    const decomp = decompose(g, target);
    if (decomp === "passthrough") {
      out.push(cloneGate(g));
    } else if (decomp === "skip") {
      skipped.push({ gateId: g.gateId, reason: `no ${target} decomposition for ${g.gateId}` });
      out.push(cloneGate(g));
    } else {
      out.push(...decomp);
    }
  }

  // ASAP re-pack of columns.
  const nextColForQ = new Array<number>(circuit.numQubits).fill(0);
  const nextColForC = new Array<number>(circuit.numClbits).fill(0);
  for (const g of out) {
    const qs = [...g.controls, ...g.targets];
    let col = 0;
    for (const q of qs) col = Math.max(col, nextColForQ[q] ?? 0);
    for (const c of g.clbits) col = Math.max(col, nextColForC[c] ?? 0);
    g.column = col;
    for (const q of qs) nextColForQ[q] = col + 1;
    for (const c of g.clbits) nextColForC[c] = col + 1;
  }

  const result: Circuit = {
    numQubits: circuit.numQubits,
    numClbits: circuit.numClbits,
    name: circuit.name ? `${circuit.name} → ${target}` : `transpiled → ${target}`,
    gates: out,
  };
  const after = countMetrics(out);
  return { circuit: result, before, after, skipped };
}

function cloneGate(g: PlacedGate): PlacedGate {
  return {
    ...g,
    id: newGateId(),
    params: [...g.params],
    controls: [...g.controls],
    targets: [...g.targets],
    clbits: [...g.clbits],
    controlStates: g.controlStates ? [...g.controlStates] : undefined,
    condition: g.condition ? { ...g.condition } : undefined,
  };
}

type Decomp = "passthrough" | "skip" | PlacedGate[];

function decompose(g: PlacedGate, target: TranspileTarget): Decomp {
  // Markers / measurements / state-prep / control flow — passthrough.
  if (
    g.gateId === "barrier" || g.gateId === "delay" ||
    g.gateId === "measure" || g.gateId === "measure_x" || g.gateId === "measure_y" ||
    g.gateId === "reset" ||
    g.gateId.startsWith("init") ||
    g.gateId === "if" || g.gateId === "while" || g.gateId === "switch" || g.gateId === "box"
  ) return "passthrough";

  if (target === "clifford-t") return decomposeCliffordT(g);
  if (target === "ibm-heavy-hex") return decomposeIBM(g);
  if (target === "rigetti") return decomposeRigetti(g);
  return "passthrough";
}

function single(g: PlacedGate, gateId: string, params: string[] = []): PlacedGate {
  return {
    ...cloneGate(g),
    gateId,
    params,
    controls: [],
    targets: [g.targets[0] ?? g.controls[0]],
  };
}

function twoQ(g: PlacedGate, gateId: string, control: number, target: number, params: string[] = []): PlacedGate {
  return {
    ...cloneGate(g),
    gateId,
    params,
    controls: [control],
    targets: [target],
  };
}

// ─── Clifford + T target ───────────────────────────────────────────────

function decomposeCliffordT(g: PlacedGate): Decomp {
  // {I, X, Y, Z, H, S, S†, T, T†, CX} pass through.
  const cliffordT = new Set(["i", "x", "y", "z", "h", "s", "sdg", "t", "tdg", "cx"]);
  if (cliffordT.has(g.gateId)) return "passthrough";

  switch (g.gateId) {
    case "cy": {
      const c = g.controls[0], t = g.targets[0];
      return [single(g, "sdg"), twoQ(g, "cx", c, t), single(g, "s")];
    }
    case "cz": {
      const c = g.controls[0], t = g.targets[0];
      return [single({ ...g, targets: [t] }, "h"), twoQ(g, "cx", c, t), single({ ...g, targets: [t] }, "h")];
    }
    case "swap": {
      const [a, b] = g.targets;
      return [twoQ(g, "cx", a, b), twoQ(g, "cx", b, a), twoQ(g, "cx", a, b)];
    }
    case "sx": {
      const t = g.targets[0];
      return [single({ ...g, targets: [t] }, "h"), single({ ...g, targets: [t] }, "s"), single({ ...g, targets: [t] }, "h")];
    }
    case "sxdg": {
      const t = g.targets[0];
      return [single({ ...g, targets: [t] }, "h"), single({ ...g, targets: [t] }, "sdg"), single({ ...g, targets: [t] }, "h")];
    }
    case "ccx": {
      const [a, b] = g.controls; const t = g.targets[0];
      return cliffordTToffoli(g, a, b, t);
    }
    case "ccz": {
      const [a, b] = g.controls; const t = g.targets[0];
      return [
        single({ ...g, targets: [t] }, "h"),
        ...cliffordTToffoli(g, a, b, t),
        single({ ...g, targets: [t] }, "h"),
      ];
    }
  }
  return "skip";
}

/** Standard 6-CX + 7-T Clifford+T decomposition of CCX(a, b, t). */
function cliffordTToffoli(template: PlacedGate, a: number, b: number, t: number): PlacedGate[] {
  const sng = (id: string, q: number) => ({
    ...cloneGate(template), gateId: id, params: [], controls: [], targets: [q],
  });
  const cx = (c: number, tt: number) => ({
    ...cloneGate(template), gateId: "cx", params: [], controls: [c], targets: [tt],
  });
  return [
    sng("h", t),
    cx(b, t), sng("tdg", t),
    cx(a, t), sng("t", t),
    cx(b, t), sng("tdg", t),
    cx(a, t), sng("t", b), sng("t", t), sng("h", t),
    cx(a, b), sng("t", a), sng("tdg", b),
    cx(a, b),
  ];
}

// ─── IBM heavy-hex (RZ, SX, CX) target ─────────────────────────────────

function decomposeIBM(g: PlacedGate): Decomp {
  const ibm = new Set(["i", "rz", "sx", "cx"]);
  if (ibm.has(g.gateId)) return "passthrough";

  const t = g.targets[0];
  const sing = (id: string, params: string[] = []) =>
    ({ ...cloneGate(g), gateId: id, params, controls: [], targets: [t] });

  switch (g.gateId) {
    case "x": return [sing("rz", ["π"]), sing("sx"), sing("sx"), sing("rz", ["π"])];
    case "y": return [sing("rz", ["π/2"]), sing("sx"), sing("sx"), sing("rz", ["-π/2"])];
    case "z": return [sing("rz", ["π"])];
    case "h": return [sing("rz", ["π/2"]), sing("sx"), sing("rz", ["π/2"])];
    case "s": return [sing("rz", ["π/2"])];
    case "sdg": return [sing("rz", ["-π/2"])];
    case "t": return [sing("rz", ["π/4"])];
    case "tdg": return [sing("rz", ["-π/4"])];
    case "sxdg": return [sing("rz", ["π"]), sing("sx"), sing("rz", ["π"])];
    case "rx": return [sing("rz", ["π/2"]), sing("sx"), sing("rz", [`${g.params[0]} + π`]), sing("sx"), sing("rz", ["5π/2"])];
    case "ry": return [sing("sx"), sing("rz", [`${g.params[0]}`]), sing("sxdg")];
    case "p":
    case "u1": return [sing("rz", [g.params[0]])];
    case "u":
    case "u3": {
      // U(θ, φ, λ) = Rz(φ) Ry(θ) Rz(λ); Ry expands as in `ry`.
      const [theta, phi, lambda] = g.params;
      return [
        sing("rz", [lambda]),
        sing("sx"),
        sing("rz", [theta]),
        sing("sxdg"),
        sing("rz", [phi]),
      ];
    }
    case "cy": {
      const c = g.controls[0];
      return [
        ...(decomposeIBM(single(g, "sdg")) as PlacedGate[]),
        twoQ(g, "cx", c, t),
        ...(decomposeIBM(single(g, "s")) as PlacedGate[]),
      ];
    }
    case "cz": {
      const c = g.controls[0];
      const hOnT = (decomposeIBM(single({ ...g, targets: [t] }, "h")) as PlacedGate[]);
      return [...hOnT, twoQ(g, "cx", c, t), ...hOnT];
    }
    case "swap": {
      const [a, b] = g.targets;
      return [twoQ(g, "cx", a, b), twoQ(g, "cx", b, a), twoQ(g, "cx", a, b)];
    }
  }
  return "skip";
}

// ─── Rigetti (RZ, RX(±π/2), CZ) target ─────────────────────────────────

function decomposeRigetti(g: PlacedGate): Decomp {
  const native = new Set(["i", "rz", "cz"]);
  if (native.has(g.gateId)) return "passthrough";
  if (g.gateId === "rx" && (g.params[0] === "π/2" || g.params[0] === "-π/2")) return "passthrough";

  const t = g.targets[0];
  const sing = (id: string, params: string[] = []) =>
    ({ ...cloneGate(g), gateId: id, params, controls: [], targets: [t] });

  switch (g.gateId) {
    case "x":
      return [sing("rx", ["π/2"]), sing("rx", ["π/2"])];
    case "z":
      return [sing("rz", ["π"])];
    case "s": return [sing("rz", ["π/2"])];
    case "sdg": return [sing("rz", ["-π/2"])];
    case "t": return [sing("rz", ["π/4"])];
    case "tdg": return [sing("rz", ["-π/4"])];
    case "h":
      // H = RZ(π/2) RX(π/2) RZ(π/2)
      return [sing("rz", ["π/2"]), sing("rx", ["π/2"]), sing("rz", ["π/2"])];
    case "ry":
      // RY(θ) = RZ(-π/2) RX(θ) RZ(π/2); RX(θ) via two RX(π/2) with RZ between.
      return [
        sing("rz", ["-π/2"]),
        sing("rx", ["π/2"]),
        sing("rz", [g.params[0]]),
        sing("rx", ["π/2"]),
        sing("rz", ["π/2"]),
      ];
    case "rx":
      // Decompose arbitrary RX(θ) using the X = RX(π/2) RX(π/2) identity
      // plus RZ envelope: RX(θ) = RZ(π/2) RX(π/2) RZ(θ) RX(π/2) RZ(-π/2).
      return [
        sing("rz", ["π/2"]),
        sing("rx", ["π/2"]),
        sing("rz", [g.params[0]]),
        sing("rx", ["π/2"]),
        sing("rz", ["-π/2"]),
      ];
    case "cx": {
      const c = g.controls[0];
      const hOnT = decomposeRigetti(single({ ...g, targets: [t] }, "h")) as PlacedGate[];
      return [...hOnT, twoQ(g, "cz", c, t), ...hOnT];
    }
  }
  return "skip";
}

// ─── Metrics ───────────────────────────────────────────────────────────

function countMetrics(gates: ReadonlyArray<PlacedGate>) {
  let n = 0, cx = 0, tCount = 0, maxCol = 0;
  for (const g of gates) {
    if (g.gateId === "barrier" || g.gateId === "delay") continue;
    n++;
    if (g.gateId === "cx") cx++;
    if (g.gateId === "t" || g.gateId === "tdg") tCount++;
    if (g.column + 1 > maxCol) maxCol = g.column + 1;
  }
  return { gates: n, cx, tCount, depth: maxCol };
}
