import type { Circuit, PlacedGate } from "../editor/types";
import { newGateId } from "../editor/state";
import { buildMatrix } from "./matrices";
import type { Complex } from "./complex";
import { evalExpr } from "./expr";
import { decomposeKAK4x4 } from "./kak";

/**
 * Rewrite a circuit into a chosen target gate set.
 *
 * Target sets implemented:
 *   • "clifford-t" — {H, S, S†, T, T†, CX}. The standard fault-tolerance
 *     basis. RZ/RY/RX with non-Clifford-T angles cannot be exactly
 *     represented and are left as-is with a warning (Solovay-Kitaev /
 *     Ross-Selinger approximation is a research-grade problem that
 *     warrants its own session).
 *   • "ibm-heavy-hex" — {RZ, SX, CX}. The IBM device native set.
 *     H / S / X / Y / Z / T / RX / RY / U / U3 all decompose into
 *     RZ·SX combinations.
 *   • "rigetti" — {RZ, RX(±π/2), CZ}. Rigetti device native set.
 *
 * Decompositions are local — each gate translates independently and the
 * column scheduler is regenerated by ASAP packing. The result is a fresh
 * circuit with the same numQubits / numClbits.
 */

export type TranspileTarget = "clifford-t" | "ibm-heavy-hex" | "rigetti";

export type TranspileResult = {
  circuit: Circuit;
  before: { gates: number; cx: number; tCount: number; depth: number };
  after: { gates: number; cx: number; tCount: number; depth: number };
  skipped: Array<{ gateId: string; reason: string }>;
};

export function transpile(circuit: Circuit, target: TranspileTarget): TranspileResult {
  const before = countMetrics(circuit.gates);
  const skipped: Array<{ gateId: string; reason: string }> = [];
  const out: PlacedGate[] = [];
  const sorted = [...circuit.gates].sort((a, b) => a.column - b.column || a.id.localeCompare(b.id));

  for (const g of sorted) {
    const decomp = decompose(g, target);
    if (decomp === "passthrough") {
      out.push(cloneGate(g));
    } else if (decomp === "skip") {
      skipped.push({ gateId: g.gateId, reason: `no ${target} decomposition for ${g.gateId}` });
      out.push(cloneGate(g));
    } else {
      // Fully reduce to the native set — a single decompose pass can leave
      // non-native intermediates (e.g. IBM's U3 → … SXdg …).
      out.push(...lowerEach(decomp, target));
    }
  }

  // ASAP re-pack of columns.
  const nextColForQ = new Array<number>(circuit.numQubits).fill(0);
  const nextColForC = new Array<number>(circuit.numClbits).fill(0);
  for (const g of out) {
    const qs = [...g.controls, ...g.targets];
    let col = 0;
    for (const q of qs) col = Math.max(col, nextColForQ[q] ?? 0);
    for (const c of g.clbits) col = Math.max(col, nextColForC[c] ?? 0);
    g.column = col;
    for (const q of qs) nextColForQ[q] = col + 1;
    for (const c of g.clbits) nextColForC[c] = col + 1;
  }

  const result: Circuit = {
    numQubits: circuit.numQubits,
    numClbits: circuit.numClbits,
    name: circuit.name ? `${circuit.name} → ${target}` : `transpiled → ${target}`,
    gates: out,
  };
  const after = countMetrics(out);
  return { circuit: result, before, after, skipped };
}

function cloneGate(g: PlacedGate): PlacedGate {
  return {
    ...g,
    id: newGateId(),
    params: [...g.params],
    controls: [...g.controls],
    targets: [...g.targets],
    clbits: [...g.clbits],
    controlStates: g.controlStates ? [...g.controlStates] : undefined,
    condition: g.condition ? { ...g.condition } : undefined,
  };
}

type Decomp = "passthrough" | "skip" | PlacedGate[];

function decompose(g: PlacedGate, target: TranspileTarget): Decomp {
  // Markers / measurements / state-prep / control flow — passthrough.
  if (
    g.gateId === "barrier" || g.gateId === "delay" ||
    g.gateId === "measure" || g.gateId === "measure_x" || g.gateId === "measure_y" ||
    g.gateId === "reset" ||
    g.gateId.startsWith("init") ||
    g.gateId === "if" || g.gateId === "while" || g.gateId === "switch" || g.gateId === "box"
  ) return "passthrough";

  if (target === "clifford-t") return decomposeCliffordT(g);
  if (target === "ibm-heavy-hex") return decomposeIBM(g);
  if (target === "rigetti") return decomposeRigetti(g);
  return "passthrough";
}

function single(g: PlacedGate, gateId: string, params: string[] = []): PlacedGate {
  return {
    ...cloneGate(g),
    gateId,
    params,
    controls: [],
    targets: [g.targets[0] ?? g.controls[0]],
  };
}

function twoQ(g: PlacedGate, gateId: string, control: number, target: number, params: string[] = []): PlacedGate {
  return {
    ...cloneGate(g),
    gateId,
    params,
    controls: [control],
    targets: [target],
  };
}

// ─── General 2-qubit decomposition (KAK + Ising lowering) ──────────────
//
// KAK is wired into the continuous-angle targets (IBM heavy-hex and
// Rigetti). Clifford+T can't represent arbitrary single-qubit angles
// exactly (no Solovay-Kitaev), so it leaves generic 2-qubit unitaries
// skipped.

const CONTINUOUS_TARGETS = new Set<TranspileTarget>(["ibm-heavy-hex", "rigetti"]);

function targetDecompose(g: PlacedGate, target: TranspileTarget): Decomp {
  if (target === "ibm-heavy-hex") return decomposeIBM(g);
  if (target === "rigetti") return decomposeRigetti(g);
  return decomposeCliffordT(g);
}

/** Recursively lower a gate list to the target's native set. A target
 *  decomposer can emit non-native intermediates (e.g. IBM's U3 → … SXdg …);
 *  re-lowering each result until it bottoms out at passthrough/skip yields a
 *  truly native list. Idempotent on native gates; depth-guarded. */
function lowerEach(gates: PlacedGate[], target: TranspileTarget, depth = 0): PlacedGate[] {
  const out: PlacedGate[] = [];
  for (const g of gates) {
    const d = targetDecompose(g, target);
    if (d === "passthrough" || d === "skip") { out.push(cloneGate(g)); continue; }
    if (depth >= 8) { for (const gg of d) out.push(cloneGate(gg)); continue; }
    out.push(...lowerEach(d, target, depth + 1));
  }
  return out;
}

/** RXX/RYY/RZZ → CX + RZ + basis-change, preserving the (possibly symbolic)
 *  angle. Verified against the native gates at machine precision. */
function isingDecomp(g: PlacedGate): PlacedGate[] {
  const [a, b] = [...g.controls, ...g.targets];
  const th = g.params[0];
  const oneQ = (id: string, q: number, params: string[] = []) =>
    ({ ...cloneGate(g), gateId: id, params, controls: [], targets: [q] });
  const cxg = () => ({ ...cloneGate(g), gateId: "cx", params: [] as string[], controls: [a], targets: [b] });
  const core = [cxg(), oneQ("rz", b, [th]), cxg()];
  if (g.gateId === "rzz") return core;
  if (g.gateId === "rxx") return [oneQ("h", a), oneQ("h", b), ...core, oneQ("h", a), oneQ("h", b)];
  // ryy
  return [oneQ("rx", a, ["π/2"]), oneQ("rx", b, ["π/2"]), ...core, oneQ("rx", a, ["-π/2"]), oneQ("rx", b, ["-π/2"])];
}

/** Evaluate a parameter expression to a finite number, or null if symbolic
 *  / non-numeric (free variables make `evalExpr` throw or return NaN). */
function numericParam(src: string): number | null {
  try {
    const v = evalExpr(src, {});
    return Number.isFinite(v) ? v : null;
  } catch {
    return null;
  }
}

/**
 * Decompose an arbitrary 2-qubit gate via KAK into u3 + RXX/RYY/RZZ, then
 * lower those to the target's native set. Returns null when the gate isn't a
 * clean numeric 2-qubit unitary (symbolic params, anti-controls, condition,
 * wrong arity, KAK failure) so the caller can fall back to "skip".
 */
function kakDecompose(g: PlacedGate, target: TranspileTarget): PlacedGate[] | null {
  if (!CONTINUOUS_TARGETS.has(target)) return null;
  if (g.condition) return null;
  if (g.controlStates && g.controlStates.some((s) => s === false)) return null;
  const qubits = [...g.controls, ...g.targets];
  if (qubits.length !== 2 || qubits[0] === qubits[1]) return null;

  const nums: number[] = [];
  for (const p of g.params) {
    const v = numericParam(p);
    if (v === null) return null;
    nums.push(v);
  }
  const matRO = buildMatrix(g.gateId, nums);
  if (!matRO || matRO.length !== 4) return null;
  const mat = matRO.map((row) => row.map((e) => [e[0], e[1]] as Complex));
  const kak = decomposeKAK4x4(mat);
  if (!kak) return null;

  const [a, b] = qubits; // a = KAK qubit 0 (MSB), b = KAK qubit 1 (LSB)
  const out: PlacedGate[] = [];
  for (const kg of kak.gates) {
    if (kg.kind === "u3") {
      const q = kg.qubit === 0 ? a : b;
      const u3: PlacedGate = {
        ...cloneGate(g),
        gateId: "u3",
        params: [String(kg.theta), String(kg.phi), String(kg.lambda)],
        controls: [],
        targets: [q],
      };
      out.push(...lowerEach([u3], target));
    } else {
      const ising: PlacedGate = {
        ...cloneGate(g),
        gateId: kg.kind,
        params: [String(kg.theta)],
        controls: [],
        targets: [a, b],
      };
      out.push(...lowerEach(isingDecomp(ising), target));
    }
  }
  return out;
}

// ─── Clifford + T target ───────────────────────────────────────────────

function decomposeCliffordT(g: PlacedGate): Decomp {
  // {I, X, Y, Z, H, S, S†, T, T†, CX} pass through.
  const cliffordT = new Set(["i", "x", "y", "z", "h", "s", "sdg", "t", "tdg", "cx"]);
  if (cliffordT.has(g.gateId)) return "passthrough";

  switch (g.gateId) {
    case "cy": {
      const c = g.controls[0], t = g.targets[0];
      return [single(g, "sdg"), twoQ(g, "cx", c, t), single(g, "s")];
    }
    case "cz": {
      const c = g.controls[0], t = g.targets[0];
      return [single({ ...g, targets: [t] }, "h"), twoQ(g, "cx", c, t), single({ ...g, targets: [t] }, "h")];
    }
    case "swap": {
      const [a, b] = g.targets;
      return [twoQ(g, "cx", a, b), twoQ(g, "cx", b, a), twoQ(g, "cx", a, b)];
    }
    case "sx": {
      const t = g.targets[0];
      return [single({ ...g, targets: [t] }, "h"), single({ ...g, targets: [t] }, "s"), single({ ...g, targets: [t] }, "h")];
    }
    case "sxdg": {
      const t = g.targets[0];
      return [single({ ...g, targets: [t] }, "h"), single({ ...g, targets: [t] }, "sdg"), single({ ...g, targets: [t] }, "h")];
    }
    case "ccx": {
      const [a, b] = g.controls; const t = g.targets[0];
      return cliffordTToffoli(g, a, b, t);
    }
    case "ccz": {
      const [a, b] = g.controls; const t = g.targets[0];
      return [
        single({ ...g, targets: [t] }, "h"),
        ...cliffordTToffoli(g, a, b, t),
        single({ ...g, targets: [t] }, "h"),
      ];
    }
  }
  return "skip";
}

/** Standard 6-CX + 7-T Clifford+T decomposition of CCX(a, b, t). */
function cliffordTToffoli(template: PlacedGate, a: number, b: number, t: number): PlacedGate[] {
  const sng = (id: string, q: number) => ({
    ...cloneGate(template), gateId: id, params: [], controls: [], targets: [q],
  });
  const cx = (c: number, tt: number) => ({
    ...cloneGate(template), gateId: "cx", params: [], controls: [c], targets: [tt],
  });
  return [
    sng("h", t),
    cx(b, t), sng("tdg", t),
    cx(a, t), sng("t", t),
    cx(b, t), sng("tdg", t),
    cx(a, t), sng("t", b), sng("t", t), sng("h", t),
    cx(a, b), sng("t", a), sng("tdg", b),
    cx(a, b),
  ];
}

// ─── IBM heavy-hex (RZ, SX, CX) target ─────────────────────────────────

function decomposeIBM(g: PlacedGate): Decomp {
  const ibm = new Set(["i", "rz", "sx", "cx"]);
  if (ibm.has(g.gateId)) return "passthrough";

  const t = g.targets[0];
  const sing = (id: string, params: string[] = []) =>
    ({ ...cloneGate(g), gateId: id, params, controls: [], targets: [t] });

  switch (g.gateId) {
    case "x": return [sing("rz", ["π"]), sing("sx"), sing("sx"), sing("rz", ["π"])];
    case "y": return [sing("rz", ["π/2"]), sing("sx"), sing("sx"), sing("rz", ["-π/2"])];
    case "z": return [sing("rz", ["π"])];
    case "h": return [sing("rz", ["π/2"]), sing("sx"), sing("rz", ["π/2"])];
    case "s": return [sing("rz", ["π/2"])];
    case "sdg": return [sing("rz", ["-π/2"])];
    case "t": return [sing("rz", ["π/4"])];
    case "tdg": return [sing("rz", ["-π/4"])];
    case "sxdg": return [sing("rz", ["π"]), sing("sx"), sing("rz", ["π"])];
    case "rx": return [sing("rz", ["π/2"]), sing("sx"), sing("rz", [`${g.params[0]} + π`]), sing("sx"), sing("rz", ["5*π/2"])];
    case "ry": return [sing("sx"), sing("rz", [`${g.params[0]}`]), sing("sxdg")];
    case "p":
    case "u1": return [sing("rz", [g.params[0]])];
    case "u":
    case "u3": {
      // U(θ, φ, λ) = Rz(φ) Ry(θ) Rz(λ); Ry expands as in `ry`.
      const [theta, phi, lambda] = g.params;
      return [
        sing("rz", [lambda]),
        sing("sx"),
        sing("rz", [theta]),
        sing("sxdg"),
        sing("rz", [phi]),
      ];
    }
    case "cy": {
      const c = g.controls[0];
      return [
        ...(decomposeIBM(single(g, "sdg")) as PlacedGate[]),
        twoQ(g, "cx", c, t),
        ...(decomposeIBM(single(g, "s")) as PlacedGate[]),
      ];
    }
    case "cz": {
      const c = g.controls[0];
      const hOnT = (decomposeIBM(single({ ...g, targets: [t] }, "h")) as PlacedGate[]);
      return [...hOnT, twoQ(g, "cx", c, t), ...hOnT];
    }
    case "swap": {
      const [a, b] = g.targets;
      return [twoQ(g, "cx", a, b), twoQ(g, "cx", b, a), twoQ(g, "cx", a, b)];
    }
    case "rxx":
    case "ryy":
    case "rzz":
      return lowerEach(isingDecomp(g), "ibm-heavy-hex");
  }
  // Arbitrary 2-qubit unitaries (u_arb_2, iSWAP, DCX, ECR, RZX, XX±YY, …)
  // route through KAK; symbolic-angle gates fall through to skip.
  const kak = kakDecompose(g, "ibm-heavy-hex");
  if (kak) return kak;
  return "skip";
}

// ─── Rigetti (RZ, RX(±π/2), CZ) target ─────────────────────────────────

function decomposeRigetti(g: PlacedGate): Decomp {
  const native = new Set(["i", "rz", "cz"]);
  if (native.has(g.gateId)) return "passthrough";
  if (g.gateId === "rx" && (g.params[0] === "π/2" || g.params[0] === "-π/2")) return "passthrough";

  const t = g.targets[0];
  const sing = (id: string, params: string[] = []) =>
    ({ ...cloneGate(g), gateId: id, params, controls: [], targets: [t] });

  switch (g.gateId) {
    case "x":
      return [sing("rx", ["π/2"]), sing("rx", ["π/2"])];
    case "z":
      return [sing("rz", ["π"])];
    case "s": return [sing("rz", ["π/2"])];
    case "sdg": return [sing("rz", ["-π/2"])];
    case "t": return [sing("rz", ["π/4"])];
    case "tdg": return [sing("rz", ["-π/4"])];
    case "h":
      // H = RZ(π/2) RX(π/2) RZ(π/2)
      return [sing("rz", ["π/2"]), sing("rx", ["π/2"]), sing("rz", ["π/2"])];
    case "ry":
      // RY(θ) = RX(-π/2) RZ(θ) RX(π/2)  (matrix order; Y = RX(-π/2) Z RX(π/2)).
      // Array order is reverse of matrix order: first element applied first.
      return [
        sing("rx", ["π/2"]),
        sing("rz", [g.params[0]]),
        sing("rx", ["-π/2"]),
      ];
    case "rx":
      // RX(θ) = H·RZ(θ)·H with H = RZ(π/2) RX(π/2) RZ(π/2), which expands to
      // RX(θ) = RZ(π/2) RX(π/2) RZ(θ+π) RX(π/2) RZ(π/2)  (palindromic, so the
      // array order matches the matrix order).
      return [
        sing("rz", ["π/2"]),
        sing("rx", ["π/2"]),
        sing("rz", [`${g.params[0]} + π`]),
        sing("rx", ["π/2"]),
        sing("rz", ["π/2"]),
      ];
    case "u":
    case "u3": {
      // U(θ, φ, λ) = Rz(φ) Ry(θ) Rz(λ); Ry lowers via the rigetti rule above.
      const [theta, phi, lambda] = g.params;
      return [
        sing("rz", [lambda]),
        sing("ry", [theta]),
        sing("rz", [phi]),
      ];
    }
    case "cx": {
      const c = g.controls[0];
      const hOnT = decomposeRigetti(single({ ...g, targets: [t] }, "h")) as PlacedGate[];
      return [...hOnT, twoQ(g, "cz", c, t), ...hOnT];
    }
    case "rxx":
    case "ryy":
    case "rzz":
      return lowerEach(isingDecomp(g), "rigetti");
  }
  // Arbitrary 2-qubit unitaries (u_arb_2, iSWAP, DCX, ECR, RZX, XX±YY, …)
  // route through KAK; symbolic-angle gates fall through to skip.
  const kak = kakDecompose(g, "rigetti");
  if (kak) return kak;
  return "skip";
}

// ─── Metrics ───────────────────────────────────────────────────────────

function countMetrics(gates: ReadonlyArray<PlacedGate>) {
  let n = 0, cx = 0, tCount = 0, maxCol = 0;
  for (const g of gates) {
    if (g.gateId === "barrier" || g.gateId === "delay") continue;
    n++;
    if (g.gateId === "cx") cx++;
    if (g.gateId === "t" || g.gateId === "tdg") tCount++;
    if (g.column + 1 > maxCol) maxCol = g.column + 1;
  }
  return { gates: n, cx, tCount, depth: maxCol };
}
