/**
 * In-browser self-test: a broad, live cross-section of Quantiom's numeric
 * core, runnable from the app's "Self-test" button.
 *
 * This is a *subset* of the project's full ~1000-case Vitest suite (run in
 * Node and in CI on every commit — see `client/test/` and
 * `.github/workflows/ci.yml`), reimplemented with plain assertions so it can
 * run in the browser against the very modules powering the user's session.
 * The point is trust: a sceptical researcher presses a button and watches a
 * few hundred checks validate the engine against analytic ground truth,
 * right now, in their own browser.
 *
 * Everything runs against modules already in the app bundle, so the only
 * marginal weight is this file — and the modal dynamically imports it, so it
 * costs nothing until the dialog is opened. Each check traps its own throw
 * so one failure can never abort the run.
 *
 * Many checks are generated by sweeping the gate catalog, which is why the
 * live count is in the hundreds. They must all stay green (a CI test,
 * `test/feature-selftest.test.ts`, enforces that).
 */
import { simulate } from "../sim/simulate";
import { buildMatrix, type Matrix } from "../sim/matrices";
import { GATES } from "../editor/gates";
import type { GateDef } from "../editor/types";
import { runClifford } from "../sim/stabilizer";
import { mulberry32 } from "../sim/measure";
import { paulis, type Pauli } from "../sim/expectation";
import { estimateResources } from "../sim/resources";
import { equivalenceCheck } from "../sim/equivalence";
import { invertGate } from "../editor/inverse";
import { evalExpr } from "../sim/expr";
import { emitQasm3 } from "../qasm/emit";
import { parseQasm3 } from "../qasm/parse";
import { emitQiskit } from "../qasm/emitQiskit";
import { emitCirq } from "../qasm/emitCirq";
import { emitBraket } from "../qasm/emitBraket";
import { emitQSharp } from "../qasm/emitQSharp";
import { emitPyQuil } from "../qasm/emitPyQuil";
import { emitPytket } from "../qasm/emitPytket";
import { emitQasm2 } from "../qasm/emitQasm2";
import { emitQuantikz } from "../qasm/emitQuantikz";
import { emitStim } from "../qasm/emitStim";
import { transpile } from "../sim/transpile";
import { parsePauliSum, buildTrotterCircuit } from "../sim/trotter";
import { noisyPauliExpectation, noisyExpectationObservable } from "../sim/simulateNoisy";
import { pecExpectation } from "../sim/pec";
import { processTomography } from "../sim/tomography";
import { decomposeKAK4x4 } from "../sim/kak";
import { mutualInformationMatrix, entropyProfile } from "../sim/entanglement";
import { computePlot, validatePlotSpec, coercePlotSpec, type PlotSpec } from "../sim/plotSpec";
import { sanitizeColor, sanitizePathD, sanitizePlotScene } from "../sim/plotProgram";
import { optimiseCircuit } from "../sim/optimisePasses";
import { synthesizeStatePrep } from "../sim/statePrep";
import { synthesizeUnitary } from "../sim/unitarySynth";
import { applyReadoutError, mitigateReadout } from "../sim/readoutMitigation";
import { buildClassicalShadows, estimatePauli } from "../sim/classicalShadows";
import { routeCircuit, countConnectivityViolations } from "../sim/router";
import { executeTool, type AgentContext } from "../panels/agentTools";
import { DEFAULT_NOISE, type NoiseModel } from "../sim/noise";
import type { Complex } from "../sim/complex";
import type { Circuit, PlacedGate, GateId } from "../editor/types";

export type CheckResult = { name: string; passed: boolean; detail?: string };
export type CheckGroup = { name: string; checks: CheckResult[] };
export type SelfTestReport = {
  groups: CheckGroup[];
  passed: number;
  failed: number;
  total: number;
  durationMs: number;
};

// ── tiny builders ───────────────────────────────────────────────────────
let _id = 0;
function gate(gateId: string, targets: number[], controls: number[] = [], params: string[] = [], column = 0): PlacedGate {
  return { id: `s${_id++}`, gateId: gateId as GateId, column, controls, targets, clbits: [], params };
}
function circ(numQubits: number, gates: PlacedGate[], numClbits = 0): Circuit {
  return { numQubits, numClbits, gates: gates.map((g, i) => (g.column === 0 ? { ...g, column: i } : g)) };
}
const close = (a: number, b: number, eps = 1e-9) => Math.abs(a - b) < eps;
function probOf(res: ReturnType<typeof simulate>, label: string): number {
  const a = res.amplitudes.find((x) => x.basis === label);
  return a ? a.re * a.re + a.im * a.im : 0;
}
const P = (s: string): Pauli[] => s.split("") as Pauli[];

// ── complex-matrix utilities ────────────────────────────────────────────
function matmul(A: Matrix, B: Matrix): Matrix {
  const n = A.length, m = B[0].length, inner = B.length;
  const out: [number, number][][] = [];
  for (let i = 0; i < n; i++) {
    const row: [number, number][] = [];
    for (let j = 0; j < m; j++) {
      let re = 0, im = 0;
      for (let k = 0; k < inner; k++) {
        const a = A[i][k], b = B[k][j];
        re += a[0] * b[0] - a[1] * b[1];
        im += a[0] * b[1] + a[1] * b[0];
      }
      row.push([re, im]);
    }
    out.push(row);
  }
  return out;
}
function dagger(A: Matrix): Matrix {
  const out: [number, number][][] = [];
  for (let j = 0; j < A[0].length; j++) {
    const row: [number, number][] = [];
    for (let i = 0; i < A.length; i++) row.push([A[i][j][0], -A[i][j][1]]);
    out.push(row);
  }
  return out;
}
function isUnitary(A: Matrix, eps = 1e-9): boolean {
  const G = matmul(A, dagger(A));
  for (let i = 0; i < G.length; i++)
    for (let j = 0; j < G.length; j++)
      if (Math.abs(G[i][j][0] - (i === j ? 1 : 0)) > eps || Math.abs(G[i][j][1]) > eps) return false;
  return true;
}
function matEq(A: Matrix, B: Matrix, eps = 1e-9): boolean {
  if (A.length !== B.length) return false;
  for (let i = 0; i < A.length; i++)
    for (let j = 0; j < A[0].length; j++)
      if (Math.abs(A[i][j][0] - B[i][j][0]) > eps || Math.abs(A[i][j][1] - B[i][j][1]) > eps) return false;
  return true;
}
/** True iff M = e^{iφ}·I (a global phase times identity), to tolerance. */
function isPhaseIdentity(M: Matrix, eps = 1e-7): boolean {
  const n = M.length;
  const d0 = M[0][0];
  if (Math.abs(Math.hypot(d0[0], d0[1]) - 1) > eps) return false;
  for (let i = 0; i < n; i++)
    for (let j = 0; j < n; j++) {
      if (i === j) {
        if (Math.abs(M[i][j][0] - d0[0]) > eps || Math.abs(M[i][j][1] - d0[1]) > eps) return false;
      } else if (Math.abs(M[i][j][0]) > eps || Math.abs(M[i][j][1]) > eps) return false;
    }
  return true;
}

// Sample params per gate (mirrors the Vitest suite). u_arb / u_arb_2 get
// genuinely unitary fillings so they pass the unitarity / norm sweeps.
const GATE_PARAMS: Record<string, number[]> = {
  p: [0.7], rx: [0.7], ry: [1.1], rz: [-0.4], r: [0.7, 1.3], gpi: [0.9], gpi2: [0.5],
  u: [0.7, 1.1, -0.4], u1: [0.7], u2: [0.7, 1.1], u3: [0.7, 1.1, -0.4],
  u_arb: [Math.SQRT1_2, 0, Math.SQRT1_2, 0, Math.SQRT1_2, 0, -Math.SQRT1_2, 0],
  u_arb_2: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
  crx: [0.7], cry: [1.1], crz: [-0.4], cp: [0.7], cu: [0.7, 1.1, -0.4, 0.3], cu1: [0.7], cu3: [0.7, 1.1, -0.4],
  rxx: [0.7], ryy: [1.1], rzz: [-0.4], rzx: [0.9], xx_plus_yy: [0.7, 1.1], xx_minus_yy: [0.7, 1.1],
  fsim: [0.7, 1.1], ms: [0.4, 0.9, 1.3], mcp: [0.7], mcu: [0.7, 1.1, -0.4],
};

function nControlsOf(g: GateDef): number { return g.variableControls ? 2 : g.numControls; }
function matrixOf(g: GateDef): Matrix | null {
  return buildMatrix(g.id, GATE_PARAMS[g.id] ?? [], nControlsOf(g) || undefined);
}
/** A minimal single-gate circuit exercising gate `g` on fresh wires. */
function singleGateCircuit(g: GateDef): Circuit {
  const nc = nControlsOf(g);
  const nt = g.numTargets;
  const controls = Array.from({ length: nc }, (_, i) => i);
  const targets = Array.from({ length: nt }, (_, i) => nc + i);
  const params = (GATE_PARAMS[g.id] ?? []).map((x) => String(x));
  return circ(nc + nt, [gate(g.id, targets, controls, params)]);
}

/** Harness: collect checks into named groups, turning throws into failures. */
class Suite {
  groups: CheckGroup[] = [];
  private cur: CheckGroup | null = null;
  group(name: string) { this.cur = { name, checks: [] }; this.groups.push(this.cur); }
  check(name: string, fn: () => boolean, detailOnFail = "") {
    let passed = false, detail = detailOnFail;
    try { passed = fn(); } catch (e) { passed = false; detail = e instanceof Error ? e.message : String(e); }
    this.cur!.checks.push({ name, passed, detail: passed ? undefined : detail });
  }
}

export function runSelfTest(): SelfTestReport {
  const t0 = (typeof performance !== "undefined" ? performance.now() : Date.now());
  const s = new Suite();

  // The unitary gate catalog: every gate that builds an operator (excludes
  // measure / reset / state-prep / markers / control-flow).
  const UNITARY: GateDef[] = GATES.filter((g) => matrixOf(g) !== null);

  // ── Per-gate matrix unitarity (one check each) ─────────────────────
  s.group("Gate matrices — unitarity (U·U† = I)");
  for (const g of UNITARY) {
    s.check(`${g.id} (${g.symbol}) is unitary`, () => isUnitary(matrixOf(g)!));
  }

  // ── Known gate identities ──────────────────────────────────────────
  s.group("Gate algebra identities");
  {
    const X = buildMatrix("x", [])!, Y = buildMatrix("y", [])!, Z = buildMatrix("z", [])!;
    const H = buildMatrix("h", [])!, S = buildMatrix("s", [])!, T = buildMatrix("t", [])!;
    const I2 = buildMatrix("i", [])!;
    const iZ: Matrix = [[[0, 1], [0, 0]], [[0, 0], [0, -1]]];
    s.check("X² = I", () => matEq(matmul(X, X), I2));
    s.check("Y² = I", () => matEq(matmul(Y, Y), I2));
    s.check("Z² = I", () => matEq(matmul(Z, Z), I2));
    s.check("H² = I", () => matEq(matmul(H, H), I2));
    s.check("S² = Z", () => matEq(matmul(S, S), Z));
    s.check("T² = S", () => matEq(matmul(T, T), S));
    s.check("H·X·H = Z", () => matEq(matmul(matmul(H, X), H), Z));
    s.check("H·Z·H = X", () => matEq(matmul(matmul(H, Z), H), X));
    s.check("X·Y = i·Z", () => matEq(matmul(X, Y), iZ));
    s.check("√X·√X = X", () => matEq(matmul(buildMatrix("sx", [])!, buildMatrix("sx", [])!), X));
    s.check("CNOT is the canonical control-0/target-1 matrix", () => matEq(buildMatrix("cx", [])!, [
      [[1, 0], [0, 0], [0, 0], [0, 0]], [[0, 0], [1, 0], [0, 0], [0, 0]],
      [[0, 0], [0, 0], [0, 0], [1, 0]], [[0, 0], [0, 0], [1, 0], [0, 0]],
    ]));
  }

  // ── Per-gate inverse: invertGate yields a true matrix inverse ──────
  s.group("Gate inverses (g⁻¹ · g = e^{iφ}·I)");
  for (const g of UNITARY) {
    const inv = invertGate(gate(g.id, [0], [], (GATE_PARAMS[g.id] ?? []).map(String)));
    if (!inv) continue; // u_arb / iSWAP / DCX etc. are honestly refused — covered below
    s.check(`${g.id}⁻¹ · ${g.id} = I (up to phase)`, () => {
      const U = matrixOf(g)!;
      const invParams = (inv.params ?? []).map((p) => evalExpr(p, {}));
      const Uinv = buildMatrix(inv.gateId, invParams, nControlsOf(g) || undefined)!;
      return isPhaseIdentity(matmul(Uinv, U));
    });
  }

  // ── Per-gate norm preservation through the statevector engine ──────
  s.group("Gate application — norm preserved (Σp = 1)");
  for (const g of UNITARY) {
    s.check(`${g.id} preserves the state norm`, () => {
      const r = simulate(singleGateCircuit(g), {});
      return close(r.probabilities.reduce((a, b) => a + b, 0), 1, 1e-8);
    });
  }

  // ── Per-gate OpenQASM 3 round-trip (emit → parse → equivalent) ─────
  // Arbitrary-matrix unitaries (u_arb / u_arb_2) have no standard OpenQASM 3
  // representation, so the emitter writes them as an annotated comment by
  // design — they're checked separately below, not in the round-trip sweep.
  const ARBITRARY = new Set(["u_arb", "u_arb_2"]);
  s.group("OpenQASM 3 round-trip — per gate");
  for (const g of UNITARY) {
    if (ARBITRARY.has(g.id)) continue;
    s.check(`${g.id} round-trips through OpenQASM 3`, () => {
      const c = singleGateCircuit(g);
      const r = parseQasm3(emitQasm3(c));
      return r.ok && equivalenceCheck(c, r.circuit, [], [], {}).equivalent;
    });
  }
  for (const id of ARBITRARY) {
    s.check(`${id} is emitted as an annotated comment (no standard QASM form)`, () => {
      const g = GATES.find((x) => x.id === id)!;
      const out = emitQasm3(singleGateCircuit(g));
      return out.includes(`// ${id}(`) && /arbitrary unitary/.test(out);
    });
  }

  // ── Statevector simulator — canonical states ───────────────────────
  s.group("Statevector simulator");
  {
    s.check("X flips |0⟩ → |1⟩", () => close(probOf(simulate(circ(1, [gate("x", [0])]), {}), "1"), 1));
    s.check("H makes a uniform superposition", () => {
      const r = simulate(circ(1, [gate("h", [0])]), {});
      return close(probOf(r, "0"), 0.5) && close(probOf(r, "1"), 0.5);
    });
    s.check("H·H = I", () => close(probOf(simulate(circ(1, [gate("h", [0], [], [], 0), gate("h", [0], [], [], 1)]), {}), "0"), 1));
    s.check("Bell state = (|00⟩+|11⟩)/√2", () => {
      const r = simulate(circ(2, [gate("h", [0]), gate("cx", [1], [0])]), {});
      return close(probOf(r, "00"), 0.5) && close(probOf(r, "11"), 0.5) && close(probOf(r, "01"), 0) && close(probOf(r, "10"), 0);
    });
    s.check("Big-endian: X on qubit 0 → |100⟩", () => close(probOf(simulate(circ(3, [gate("x", [0])]), {}), "100"), 1));
    s.check("Big-endian: X on qubit 2 → |001⟩", () => close(probOf(simulate(circ(3, [gate("x", [2])]), {}), "001"), 1));
    s.check("RX(π) ≈ X: |0⟩ → |1⟩", () => close(probOf(simulate(circ(1, [gate("rx", [0], [], ["pi"])]), {}), "1"), 1));
    s.check("RY(π/2) on |0⟩ is an equal split", () => {
      const r = simulate(circ(1, [gate("ry", [0], [], ["pi/2"])]), {});
      return close(probOf(r, "0"), 0.5) && close(probOf(r, "1"), 0.5);
    });
    s.check("Bloch vector of |+⟩ points +X", () => {
      const b = simulate(circ(1, [gate("h", [0])]), {}).blochVectors[0];
      return close(b.x, 1) && close(b.z, 0);
    });
    // GHZ family across widths.
    for (let n = 2; n <= 6; n++) {
      s.check(`${n}-qubit GHZ has weight ½ on |0…0⟩ and |1…1⟩`, () => {
        const gates = [gate("h", [0])];
        for (let q = 1; q < n; q++) gates.push(gate("cx", [q], [q - 1]));
        const r = simulate(circ(n, gates), {});
        return close(probOf(r, "0".repeat(n)), 0.5) && close(probOf(r, "1".repeat(n)), 0.5);
      });
    }
  }

  // ── Stabilizer (Clifford tableau) ──────────────────────────────────
  s.group("Stabilizer tableau");
  {
    const g = (id: string, t: number[], c: number[] = [], cl: number[] = []) => ({ gateId: id, targets: t, controls: c, clbits: cl });
    s.check("Bell outcomes perfectly correlated", () => {
      for (let seed = 0; seed < 25; seed++) {
        const { classical } = runClifford(2, [g("h", [0]), g("cx", [1], [0]), g("measure", [0], [], [0]), g("measure", [1], [], [1])], mulberry32(seed + 1), 2);
        if (classical[0] !== classical[1]) return false;
      }
      return true;
    });
    s.check("X·measure deterministically yields 1", () => runClifford(1, [g("x", [0]), g("measure", [0], [], [0])], mulberry32(5), 1).classical[0] === 1);
    for (const n of [3, 8, 16, 40]) {
      s.check(`${n}-qubit GHZ: every shot is all-equal (tableau)`, () => {
        const gates = [g("h", [0])];
        for (let q = 1; q < n; q++) gates.push(g("cx", [q], [q - 1]));
        for (let q = 0; q < n; q++) gates.push(g("measure", [q], [], [q]));
        for (let seed = 0; seed < 5; seed++) {
          const { classical } = runClifford(n, gates, mulberry32(seed + 1), n);
          if (![...classical].every((b) => b === classical[0])) return false;
        }
        return true;
      });
    }
  }

  // ── Pauli expectations ─────────────────────────────────────────────
  s.group("Pauli expectations");
  {
    s.check("⟨Z⟩ = +1 on |0⟩", () => close(paulis(simulate(circ(1, []), {}).state, 1, P("Z")), 1));
    s.check("⟨Z⟩ = −1 on |1⟩", () => close(paulis(simulate(circ(1, [gate("x", [0])]), {}).state, 1, P("Z")), -1));
    s.check("⟨X⟩ = +1 on |+⟩", () => close(paulis(simulate(circ(1, [gate("h", [0])]), {}).state, 1, P("X")), 1));
    s.check("⟨X⟩ = −1 on |−⟩", () => close(paulis(simulate(circ(1, [gate("x", [0], [], [], 0), gate("h", [0], [], [], 1)]), {}).state, 1, P("X")), -1));
    s.check("⟨Y⟩ = +1 on S·H·|0⟩", () => close(paulis(simulate(circ(1, [gate("h", [0]), gate("s", [0])]), {}).state, 1, P("Y")), 1));
    const bell = simulate(circ(2, [gate("h", [0]), gate("cx", [1], [0])]), {}).state;
    s.check("Bell ⟨ZZ⟩ = +1", () => close(paulis(bell, 2, P("ZZ")), 1));
    s.check("Bell ⟨XX⟩ = +1", () => close(paulis(bell, 2, P("XX")), 1));
    s.check("Bell ⟨YY⟩ = −1", () => close(paulis(bell, 2, P("YY")), -1));
    s.check("Bell ⟨ZI⟩ = 0", () => close(paulis(bell, 2, P("ZI")), 0));
    s.check("⟨II⟩ = 1 on any state", () => close(paulis(bell, 2, P("II")), 1));
  }

  // ── OpenQASM round-trip — multi-gate circuits ──────────────────────
  s.group("OpenQASM 3 round-trip — circuits");
  {
    const rt = (c: Circuit) => { const r = parseQasm3(emitQasm3(c)); return r.ok && equivalenceCheck(c, r.circuit, [], [], {}).equivalent; };
    s.check("Bell round-trips", () => rt(circ(2, [gate("h", [0]), gate("cx", [1], [0])])));
    s.check("GHZ + Toffoli round-trips", () => rt(circ(3, [gate("h", [0]), gate("cx", [1], [0]), gate("ccx", [2], [0, 1])])));
    s.check("Rotations round-trip", () => rt(circ(2, [gate("rx", [0], [], ["pi/2"]), gate("ry", [1], [], ["0.7"]), gate("rzz", [1], [0], ["1.3"])])));
    s.check("Anti-control round-trips", () => rt(circ(2, [{ ...gate("cx", [1], [0]), controlStates: [false] }])));
    s.check("Emit is idempotent", () => {
      const c = circ(2, [gate("h", [0]), gate("cx", [1], [0]), gate("rz", [1], [], ["pi/4"])]);
      const once = emitQasm3(c);
      const r = parseQasm3(once);
      return r.ok && emitQasm3(r.circuit) === once;
    });
  }

  // ── SDK code exports (each emitter × several circuits) ─────────────
  s.group("SDK code exports");
  {
    const emitters: Array<[string, (c: Circuit) => string, RegExp]> = [
      ["Qiskit", emitQiskit, /QuantumCircuit/], ["Cirq", emitCirq, /cirq/], ["Braket", emitBraket, /Circuit/],
      ["Q#", emitQSharp, /operation/], ["PyQuil", emitPyQuil, /Program/], ["pytket", emitPytket, /Circuit/],
      ["OpenQASM 2", emitQasm2, /OPENQASM 2/], ["quantikz", emitQuantikz, /\\/],
    ];
    const circuits: Array<[string, Circuit]> = [
      ["Bell", circ(2, [gate("h", [0]), gate("cx", [1], [0])])],
      ["GHZ+Toffoli", circ(3, [gate("h", [0]), gate("cx", [1], [0]), gate("ccx", [2], [0, 1])])],
      ["rotations", circ(2, [gate("rx", [0], [], ["pi/2"]), gate("ry", [1], [], ["0.7"]), gate("cx", [1], [0])])],
      ["single-qubit", circ(1, [gate("h", [0]), gate("t", [0]), gate("s", [0])])],
    ];
    for (const [ename, fn, sig] of emitters)
      for (const [cname, c] of circuits)
        s.check(`${ename} export — ${cname}`, () => { const out = fn(c); return out.length > 15 && sig.test(out); });
  }

  // ── Transpiler ─────────────────────────────────────────────────────
  s.group("Transpiler preserves the unitary");
  {
    const rotCircuits: Array<[string, Circuit]> = [
      ["RY+CX+RZ", circ(2, [gate("h", [0]), gate("ry", [1], [], ["0.7"]), gate("cx", [1], [0]), gate("rz", [0], [], ["pi/3"])])],
      ["RX+RZ", circ(1, [gate("rx", [0], [], ["0.9"]), gate("rz", [0], [], ["1.2"])])],
      ["Bell", circ(2, [gate("h", [0]), gate("cx", [1], [0])])],
    ];
    for (const target of ["ibm-heavy-hex", "rigetti"] as const)
      for (const [name, c] of rotCircuits)
        s.check(`${target} — ${name} equivalent`, () => equivalenceCheck(c, transpile(c, target).circuit, [], [], {}).equivalent);
    s.check("Clifford+T — Toffoli decomposition equivalent", () => {
      const c = circ(3, [gate("h", [0]), gate("cx", [1], [0]), gate("t", [1]), gate("ccx", [2], [0, 1])]);
      return equivalenceCheck(c, transpile(c, "clifford-t").circuit, [], [], {}).equivalent;
    });
  }

  // ── Trotter synthesis ──────────────────────────────────────────────
  s.group("Trotter synthesis");
  {
    s.check("e^{-iδX} on |0⟩ = RX(2δ)", () => close(probOf(simulate(buildTrotterCircuit(parsePauliSum("1.0 X"), { steps: 1, delta: "t" }), { t: Math.PI / 4 }), "1"), 0.5));
    s.check("Z-only Hamiltonian preserves populations", () => close(probOf(simulate(buildTrotterCircuit(parsePauliSum("1.0 Z"), { steps: 2, delta: "t" }), { t: 0.6 }), "0"), 1));
    for (const order of [1, 2, 4] as const)
      s.check(`order-${order} TFIM step builds a normalized circuit`, () => {
        const c = buildTrotterCircuit(parsePauliSum("0.5 ZZ + 0.3 XI + 0.3 IX"), { steps: 2, delta: "t", order });
        return close(simulate(c, { t: 0.2 }).probabilities.reduce((a, b) => a + b, 0), 1, 1e-8);
      });
  }

  // ── Equivalence & resources ────────────────────────────────────────
  s.group("Equivalence & resources");
  {
    const eq = (a: Circuit, b: Circuit) => equivalenceCheck(a, b, [], [], {}).equivalent;
    s.check("A circuit equals itself", () => eq(circ(2, [gate("h", [0]), gate("cx", [1], [0])]), circ(2, [gate("h", [0]), gate("cx", [1], [0])])));
    s.check("Two CNOTs cancel", () => eq(circ(2, [gate("cx", [1], [0], [], 0), gate("cx", [1], [0], [], 1)]), circ(2, [])));
    s.check("H·CZ·H = CNOT", () => eq(circ(2, [gate("h", [1], [], [], 0), gate("cz", [1], [0], [], 1), gate("h", [1], [], [], 2)]), circ(2, [gate("cx", [1], [0])])));
    s.check("X and Z are NOT equivalent", () => !eq(circ(1, [gate("x", [0])]), circ(1, [gate("z", [0])])));
    s.check("iSWAP is correctly refused by invertGate", () => invertGate(gate("iswap", [0, 1])) === null);
    s.check("Resource counts (T-count, CX, total)", () => {
      const r = estimateResources(circ(2, [gate("cx", [1], [0]), gate("t", [0], [], [], 1), gate("h", [0], [], [], 2)]));
      return r.tCount === 1 && r.cxCount === 1 && r.totalGates === 3;
    });
  }

  // ── Mid-circuit measurement & reset (statevector) ──────────────────
  s.group("Measurement & reset");
  {
    const measured = (gates: PlacedGate[]) => simulate(circ(1, gates, 1), {});
    s.check("X then Z-measure collapses to |1⟩", () =>
      close(probOf(measured([gate("x", [0]), { ...gate("measure", [0], [], [], 1), clbits: [0] }]), "1"), 1));
    s.check("reset returns any state to |0⟩", () =>
      close(probOf(measured([gate("x", [0]), gate("reset", [0], [], [], 1)]), "0"), 1));
    s.check("X-basis measure of |+⟩ is deterministic (outcome preserved)", () => {
      // H|0⟩ = |+⟩; measure_x rotates to Z, measures, rotates back ⇒ stays |+⟩.
      const r = simulate(circ(1, [gate("h", [0]), { ...gate("measure_x", [0], [], [], 1), clbits: [0] }], 1), {});
      return close(probOf(r, "0"), 0.5) && close(probOf(r, "1"), 0.5);
    });
  }

  // ── initialize() state-prep gate ───────────────────────────────────
  s.group("State preparation — initialize()");
  {
    const init = (label: string, p = {}) => simulate(circ(1, [gate("initialize", [0], [], [label])]), p);
    s.check("initialize |1⟩", () => close(probOf(init("|1⟩"), "1"), 1));
    s.check("initialize |+⟩ is an equal split", () => close(probOf(init("|+⟩"), "0"), 0.5) && close(probOf(init("|+⟩"), "1"), 0.5));
    s.check("initialize |+i⟩ puts the phase on +Y", () => {
      const a = init("|+i⟩").amplitudes.find((x) => x.basis === "1")!;
      return close(a.re, 0) && close(a.im, Math.SQRT1_2);
    });
    s.check("amplitude tuple (0,0,1,0) = |1⟩", () => close(probOf(init("(0, 0, 1, 0)"), "1"), 1));
    s.check("amplitude tuple with a bound parameter ((cos t,0,sin t,0), t=π/2) = |1⟩", () =>
      close(probOf(init("(cos(t), 0, sin(t), 0)", { t: Math.PI / 2 }), "1"), 1));
    s.check("an un-normalised tuple is normalised", () => close(probOf(init("(2, 0, 0, 0)"), "0"), 1));
  }

  // ── Trajectory noise simulator (exact at zero noise) ───────────────
  s.group("Noisy simulator — zero-noise exactness");
  {
    const noiseless: NoiseModel = {
      ...DEFAULT_NOISE, enabled: true, trajectories: 1,
      oneQubitDepolarising: 0, twoQubitDepolarising: 0, amplitudeDamping: 0,
      phaseDamping: 0, readoutBitFlip: 0, crosstalk: 0,
    };
    const ry = circ(1, [gate("ry", [0], [], ["pi/3"])]); // ⟨Z⟩ = cos(π/3) = 0.5
    s.check("noisyPauliExpectation ⟨Z⟩ matches the analytic 0.5", () =>
      close(noisyPauliExpectation(ry, {}, [], noiseless, P("Z")), 0.5, 1e-9));
    s.check("Pauli-sum observable H = ½Z gives ⟨H⟩ = 0.25", () =>
      close(noisyExpectationObservable(ry, {}, [], noiseless, { kind: "sum", terms: [{ coefficient: 0.5, paulis: "Z" }] }), 0.25, 1e-9));
    s.check("post-selection on a forced X·measure outcome conditions ⟨Z⟩ = −1", () => {
      const c: Circuit = { numQubits: 1, numClbits: 1, gates: [gate("x", [0], [], [], 0), { ...gate("measure", [0], [], [], 1), clbits: [0] }] };
      return close(noisyExpectationObservable(c, {}, [], noiseless, { kind: "pauli", paulis: P("Z") }, { clbit: 0, value: 1 }), -1, 1e-9);
    });
  }

  // ── Probabilistic Error Cancellation (exact at zero noise) ─────────
  s.group("Probabilistic Error Cancellation");
  {
    const noiseless: NoiseModel = {
      ...DEFAULT_NOISE, enabled: true, trajectories: 1,
      oneQubitDepolarising: 0, twoQubitDepolarising: 0, amplitudeDamping: 0,
      phaseDamping: 0, readoutBitFlip: 0, crosstalk: 0,
    };
    const ry = circ(1, [gate("ry", [0], [], ["pi/3"])]);
    s.check("PEC at zero noise returns the ideal ⟨Z⟩ with overhead 1", () => {
      const r = pecExpectation(ry, {}, [], noiseless, { kind: "pauli", paulis: P("Z") }, 16);
      return close(r.value, 0.5, 1e-9) && close(r.varianceOverhead, 1, 1e-9);
    });
    s.check("PEC reports the inverted-channel location counts", () => {
      const r = pecExpectation(ry, {}, [], noiseless, { kind: "pauli", paulis: P("Z") }, 4);
      return r.channels.oneQDepol === 1 && r.uninverted.length === 0;
    });
  }

  // ── Process tomography ──────────────────────────────────────────────
  s.group("Process tomography");
  {
    const dominant = (r: ReturnType<typeof processTomography>) => {
      let best = 0;
      for (let i = 1; i < r.beta.length; i++)
        if (Math.hypot(r.beta[i].re, r.beta[i].im) > Math.hypot(r.beta[best].re, r.beta[best].im)) best = i;
      return r.labels[best];
    };
    s.check("X gate decomposes onto the X Pauli", () => dominant(processTomography(circ(1, [gate("x", [0])]), {}, [])) === "X");
    s.check("identity decomposes onto I", () => dominant(processTomography(circ(1, [gate("i", [0])]), {}, [])) === "I");
    s.check("χ is trace-normalised (Σ|β|² = 1) for a unitary process", () => {
      const r = processTomography(circ(1, [gate("ry", [0], [], ["0.9"])]), {}, []);
      return close(r.beta.reduce((a, b) => a + b.re * b.re + b.im * b.im, 0), 1, 1e-8);
    });
    s.check("CX (2-qubit Kronecker path) spreads over II/IX/ZI/ZX", () => {
      const r = processTomography(circ(2, [gate("cx", [1], [0])]), {}, []);
      const big = r.labels.filter((_, i) => Math.hypot(r.beta[i].re, r.beta[i].im) > 0.4).sort();
      return big.join(",") === "II,IX,ZI,ZX";
    });
  }

  // ── KAK 2-qubit decomposition ───────────────────────────────────────
  s.group("KAK decomposition (Cartan)");
  {
    const I_C: Complex = [1, 0], Z_C: Complex = [0, 0];
    const eye4 = (): Complex[][] => { const m = Array.from({ length: 4 }, () => Array.from({ length: 4 }, () => Z_C)); for (let i = 0; i < 4; i++) m[i][i] = I_C; return m; };
    const cnot = (): Complex[][] => { const m = eye4(); [m[2], m[3]] = [m[3], m[2]]; return m; };
    const swap = (): Complex[][] => { const m = eye4(); [m[1], m[2]] = [m[2], m[1]]; return m; };
    s.check("CNOT decomposes with machine-precision residual", () => {
      const r = decomposeKAK4x4(cnot());
      return r !== null && r.residual < 1e-6;
    });
    s.check("SWAP decomposes with machine-precision residual", () => {
      const r = decomposeKAK4x4(swap());
      return r !== null && r.residual < 1e-6;
    });
    s.check("identity decomposes cleanly", () => {
      const r = decomposeKAK4x4(eye4());
      return r !== null && r.residual < 1e-6;
    });
  }

  // ── Entanglement metrics (visualiser substrates) ───────────────────
  s.group("Entanglement metrics");
  {
    const bell = simulate(circ(2, [gate("h", [0]), gate("cx", [1], [0])]), {}).state;
    const product = simulate(circ(2, [gate("h", [0]), gate("h", [1])]), {}).state;
    s.check("Bell: each qubit's marginal entropy = 1 bit", () => {
      const mi = mutualInformationMatrix(bell, 2)!;
      return close(mi.single[0], 1, 1e-6) && close(mi.single[1], 1, 1e-6);
    });
    s.check("Bell: mutual information I(0:1) = 2 bits", () => close(mutualInformationMatrix(bell, 2)!.mi[0][1], 2, 1e-6));
    s.check("Product state: zero mutual information", () => close(mutualInformationMatrix(product, 2)!.mi[0][1], 0, 1e-6));
    s.check("GHZ-3: every contiguous cut carries 1 bit", () => {
      const ghz = simulate(circ(3, [gate("h", [0]), gate("cx", [1], [0]), gate("cx", [2], [1])]), {}).state;
      const prof = entropyProfile(ghz, 3)!;
      return prof.entropy.every((e) => close(e, 1, 1e-6));
    });
  }

  // ── Stabilizer single-qubit Bloch reduction ────────────────────────
  s.group("Stabilizer Bloch vectors");
  {
    const bloch = (n: number, gates: PlacedGate[]) => runClifford(n, gates).tab.blochVectors();
    const eq = (b: { x: number; y: number; z: number }, x: number, y: number, z: number) => b.x === x && b.y === y && b.z === z;
    s.check("|0⟩ → +Z", () => eq(bloch(1, [])[0], 0, 0, 1));
    s.check("X|0⟩ = |1⟩ → −Z", () => eq(bloch(1, [gate("x", [0])])[0], 0, 0, -1));
    s.check("H|0⟩ = |+⟩ → +X", () => eq(bloch(1, [gate("h", [0])])[0], 1, 0, 0));
    s.check("S·H|0⟩ = |+i⟩ → +Y", () => eq(bloch(1, [gate("h", [0]), gate("s", [0])])[0], 0, 1, 0));
    s.check("Bell marginals are maximally mixed (Bloch 0)", () => {
      const b = bloch(2, [gate("h", [0]), gate("cx", [1], [0])]);
      return eq(b[0], 0, 0, 0) && eq(b[1], 0, 0, 0);
    });
  }

  // ── SDK export content (not just the signature token) ──────────────
  s.group("SDK export content");
  {
    const bell = circ(2, [gate("h", [0]), gate("cx", [1], [0])]);
    s.check("Qiskit Bell emits qc.h(0) and qc.cx(0, 1)", () => { const o = emitQiskit(bell); return o.includes("qc.h(0)") && o.includes("qc.cx(0, 1)"); });
    s.check("Cirq Bell emits H and CNOT", () => { const o = emitCirq(bell); return o.includes("cirq.H(qs[0])") && o.includes("cirq.CNOT(qs[0], qs[1])"); });
    s.check("Q# Bell emits H and CNOT", () => { const o = emitQSharp(bell); return o.includes("H(qs[0]);") && o.includes("CNOT(qs[0], qs[1]);"); });
    s.check("Braket Bell emits h and cnot", () => { const o = emitBraket(bell); return o.includes("circuit.h(0)") && o.includes("circuit.cnot(0, 1)"); });
    s.check("OpenQASM 2 Bell emits qreg/creg-free h and cx", () => { const o = emitQasm2(bell); return o.includes("h q[0];") && o.includes("cx q[0], q[1];"); });
    s.check("quantikz Bell emits a gate and a CNOT target", () => { const o = emitQuantikz(bell); return o.includes("\\gate{H}") && o.includes("\\targ{}"); });
    s.check("Stim Bell emits H 0 and CX 0 1", () => { const o = emitStim(bell); return /^H 0$/m.test(o) && /^CX 0 1$/m.test(o); });
  }

  // ── Custom plots: the on-demand plot engine + program sandbox ──────
  s.group("Custom plots (plot engine)");
  {
    const bell = circ(2, [gate("h", [0]), gate("cx", [1], [0])]);
    // 1-D series value at a given index, or NaN on error / wrong shape.
    const v0 = (spec: PlotSpec, i = 0): number => {
      const r = computePlot(spec, bell, {}, []);
      if ("error" in r || r.data.kind !== "series1d") return NaN;
      return r.data.values[i];
    };
    const matEl = (spec: PlotSpec, i: number, j: number): number => {
      const r = computePlot(spec, bell, {}, []);
      if ("error" in r || r.data.kind !== "matrix") return NaN;
      return r.data.z[i][j];
    };
    const sp = (quantity: PlotSpec["quantity"], extra: Partial<PlotSpec> = {}): PlotSpec =>
      ({ quantity, sweep: "none", chart: "bars", ...extra });

    s.check("⟨Z⟩ per qubit on a Bell pair is 0", () => close(v0(sp("expZ")), 0));
    s.check("probabilities: |00⟩ = ½", () => close(v0(sp("prob", { chart: "bars" })), 0.5));
    s.check("single-qubit entropy S(ρ_q) = 1 bit", () => close(v0(sp("qubitEntropy")), 1, 1e-7));
    s.check("mutual information I(0:1) = 2 bits", () => close(matEl(sp("mutualInfo", { chart: "heatmap" }), 0, 1), 2, 1e-7));
    s.check("log-negativity E_N(0:1) = 1 ebit", () => close(matEl(sp("negativity", { chart: "heatmap" }), 0, 1), 1, 1e-7));
    s.check("concurrence C(0:1) = 1", () => close(matEl(sp("concurrence", { chart: "heatmap" }), 0, 1), 1, 1e-7));
    s.check("connected ⟨X₀X₁⟩ = +1", () => close(matEl(sp("xxCorr", { chart: "heatmap" }), 0, 1), 1, 1e-7));
    s.check("connected ⟨Y₀Y₁⟩ = −1", () => close(matEl(sp("yyCorr", { chart: "heatmap" }), 0, 1), -1, 1e-7));
    s.check("mid-cut entropy = 1 bit", () => close(v0(sp("midEntropy")), 1, 1e-7));
    s.check("Meyer–Wallach Q = 1", () => close(v0(sp("meyerWallach")), 1, 1e-7));
    s.check("participation entropy = 1 bit", () => close(v0(sp("participationEntropy")), 1, 1e-7));
    s.check("magic M₂ = 0 for a Clifford state", () => close(v0(sp("magic")), 0, 1e-6));
    s.check("custom ⟨ZZ⟩ = 1", () => close(v0(sp("pauli", { args: { pauli: "ZZ" } })), 1, 1e-7));
    s.check("energy ⟨ZZ + XX⟩ = 2", () => close(v0(sp("energy", { args: { hamiltonian: "ZZ + XX" } })), 2, 1e-7));
    s.check("entanglement spectrum at the cut is {½, ½}", () => {
      const r = computePlot(sp("schmidt", { args: { cut: 1 } }), bell, {}, []);
      return !("error" in r) && r.data.kind === "series1d" && close(r.data.values[0], 0.5, 1e-7) && close(r.data.values[1], 0.5, 1e-7);
    });
    s.check("amplitude scatter puts |00⟩ at Re ≈ 1/√2", () => {
      const r = computePlot(sp("ampScatter", { chart: "scatter" }), bell, {}, []);
      return !("error" in r) && r.data.kind === "scatter" && close(r.data.points[0].x, Math.SQRT1_2, 1e-7);
    });
    s.check("unitary |U_ij| of H is 1/√2", () => {
      const hc = circ(1, [gate("h", [0])]);
      const r = computePlot(sp("unitaryMag", { chart: "heatmap" }), hc, {}, []);
      return !("error" in r) && r.data.kind === "matrix" && close(r.data.z[0][0], Math.SQRT1_2, 1e-7);
    });
    s.check("energy spectrum of H = Z is {−1, +1}", () => {
      const r = computePlot(sp("energySpectrum", { args: { hamiltonian: "Z" } }), circ(1, []), {}, []);
      return !("error" in r) && r.data.kind === "series1d" && close(Math.min(...r.data.values), -1, 1e-7) && close(Math.max(...r.data.values), 1, 1e-7);
    });
    // validation + coercion
    s.check("validate rejects a matrix quantity drawn as bars", () => validatePlotSpec(sp("mutualInfo")) !== null);
    s.check("validate rejects a pauli plot with no args", () => validatePlotSpec(sp("pauli")) !== null);
    s.check("coerce repairs an impossible chart (matrix → heatmap)", () => coercePlotSpec({ quantity: "zzCorr", chart: "bars" })?.chart === "heatmap");
    s.check("coerce normalises a Pauli arg to upper-case", () => coercePlotSpec({ quantity: "pauli", args: { pauli: "zx" } })?.args?.pauli === "ZX");
  }

  // ── Custom plots: the program sandbox sanitisers ───────────────────
  s.group("Custom plots (sandbox sanitisers)");
  {
    s.check("colour: hex accepted", () => sanitizeColor("#1a2b3c") === "#1a2b3c");
    s.check("colour: var(--accent) accepted", () => sanitizeColor("var(--accent)") === "var(--accent)");
    s.check("colour: url(...) injection → fallback", () => sanitizeColor("url(http://evil)") === "var(--accent)");
    s.check("colour: javascript: → fallback", () => sanitizeColor("javascript:alert(1)") === "var(--accent)");
    s.check("path: valid SVG data accepted", () => sanitizePathD("M0 0 L10 10 Z") === "M0 0 L10 10 Z");
    s.check("path: markup injection → null", () => sanitizePathD("M0 0 </path><script>") === null);
    s.check("scene: missing elements → error", () => "error" in sanitizePlotScene({ width: 100 }));
    s.check("scene: unknown element type dropped, valid kept", () => {
      const r = sanitizePlotScene({ elements: [{ type: "bogus" }, { type: "line", x1: 0, y1: 0, x2: 1, y2: 1 }] });
      return !("error" in r) && r.scene.elements.length === 1;
    });
    s.check("scene: NaN coordinates clamped finite", () => {
      const r = sanitizePlotScene({ elements: [{ type: "circle", cx: Infinity, cy: NaN, r: 5 }] });
      return !("error" in r) && r.scene.elements[0].type === "circle" && Number.isFinite((r.scene.elements[0] as { cx: number }).cx);
    });
    s.check("scene: element count capped at 4000", () => {
      const many = Array.from({ length: 9000 }, () => ({ type: "line", x1: 0, y1: 0, x2: 1, y2: 1 }));
      const r = sanitizePlotScene({ elements: many });
      return !("error" in r) && r.scene.elements.length <= 4000;
    });
  }

  // ── Optimiser (peephole rewrite passes) ────────────────────────────
  s.group("Optimiser (peephole passes)");
  {
    s.check("H·H cancels to an empty circuit", () =>
      optimiseCircuit(circ(1, [gate("h", [0], [], [], 0), gate("h", [0], [], [], 1)])).after === 0);
    s.check("T·T merges to S", () => {
      const r = optimiseCircuit(circ(1, [gate("t", [0], [], [], 0), gate("t", [0], [], [], 1)]));
      return r.after === 1 && r.circuit.gates[0].gateId === "s";
    });
    s.check("H·CZ·H rewrites to a single CX", () => {
      const c = circ(2, [gate("h", [1], [], [], 0), gate("cz", [1], [0], [], 1), gate("h", [1], [], [], 2)]);
      const r = optimiseCircuit(c);
      return r.after === 1 && r.circuit.gates[0].gateId === "cx" && equivalenceCheck(c, r.circuit, [], [], {}).equivalent;
    });
    s.check("optimised circuit stays equivalent to the original", () => {
      const c = circ(2, [gate("h", [0], [], [], 0), gate("cx", [1], [0], [], 1), gate("t", [1], [], [], 2), gate("t", [1], [], [], 3), gate("h", [0], [], [], 4), gate("h", [0], [], [], 5)]);
      return equivalenceCheck(c, optimiseCircuit(c).circuit, [], [], {}).equivalent;
    });
  }

  // ── State-preparation synthesis (Möttönen) ─────────────────────────
  s.group("State-preparation synthesis (fidelity 1)");
  {
    const fidelity = (re: number[], im: number[], n: number): number => {
      const r = synthesizeStatePrep(re, im, n);
      if (!r) return 0;
      const st = simulate({ numQubits: n, numClbits: 0, gates: r.gates }, {}, []).state;
      let norm = 0;
      for (let i = 0; i < re.length; i++) norm += re[i] * re[i] + im[i] * im[i];
      norm = Math.sqrt(norm);
      let ipRe = 0, ipIm = 0;
      for (let i = 0; i < re.length; i++) {
        const tr = re[i] / norm, ti = im[i] / norm;
        const sr = st[2 * i], si = st[2 * i + 1];
        ipRe += tr * sr + ti * si;
        ipIm += tr * si - ti * sr;
      }
      return ipRe * ipRe + ipIm * ipIm;
    };
    s.check("prepares |1⟩ at fidelity 1", () => close(fidelity([0, 1], [0, 0], 1), 1, 1e-9));
    s.check("prepares |+⟩ at fidelity 1", () => close(fidelity([1, 1], [0, 0], 1), 1, 1e-9));
    s.check("prepares a Bell state at fidelity 1", () => close(fidelity([1, 0, 0, 1], [0, 0, 0, 0], 2), 1, 1e-9));
    s.check("prepares a phased 3-qubit state at fidelity 1", () =>
      close(fidelity([1, 0.5, 0, 0.5, 0, 0.5, 0, 0.5], [0, 0.2, 0, -0.1, 0, 0.3, 0, 0], 3), 1, 1e-7));
  }

  // ── Arbitrary-unitary synthesis (Givens two-level) ─────────────────
  s.group("Unitary synthesis (process fidelity 1)");
  {
    type Cx = { re: number; im: number };
    const unitaryOf = (c: Circuit, n: number): Cx[][] => {
      const dim = 1 << n;
      const U: Cx[][] = Array.from({ length: dim }, () => Array.from({ length: dim }, () => ({ re: 0, im: 0 })));
      for (let j = 0; j < dim; j++) {
        const st = simulate(c, {}, [], { startIndex: j }).state;
        for (let i = 0; i < dim; i++) U[i][j] = { re: st[2 * i], im: st[2 * i + 1] };
      }
      return U;
    };
    const procFid = (U: Cx[][], V: Cx[][]): number => {
      const dim = U.length;
      let re = 0, im = 0;
      for (let i = 0; i < dim; i++)
        for (let j = 0; j < dim; j++) {
          re += U[i][j].re * V[i][j].re + U[i][j].im * V[i][j].im;
          im += U[i][j].re * V[i][j].im - U[i][j].im * V[i][j].re;
        }
      return (re * re + im * im) / (dim * dim);
    };
    const rt = (c: Circuit, n: number): number => {
      const U = unitaryOf(c, n);
      const gates = synthesizeUnitary(U, n);
      if (!gates) return 0;
      return procFid(U, unitaryOf({ numQubits: n, numClbits: 0, gates }, n));
    };
    s.check("H synthesizes at fidelity 1", () => close(rt(circ(1, [gate("h", [0])]), 1), 1, 1e-7));
    s.check("T synthesizes at fidelity 1", () => close(rt(circ(1, [gate("t", [0])]), 1), 1, 1e-7));
    s.check("Bell circuit synthesizes at fidelity 1", () => close(rt(circ(2, [gate("h", [0]), gate("cx", [1], [0])]), 2), 1, 1e-7));
  }

  // ── Readout-error mitigation (confusion-matrix inversion) ──────────
  s.group("Readout-error mitigation");
  {
    s.check("forward model flips |0⟩ with probability p", () => {
      const d = applyReadoutError([1, 0], 1, 0.1);
      return close(d[0], 0.9, 1e-10) && close(d[1], 0.1, 1e-10);
    });
    s.check("mitigation inverts the forward model (1 qubit)", () => {
      const { corrected } = mitigateReadout(applyReadoutError([0.7, 0.3], 1, 0.08), 1, 0.08);
      return close(corrected[0], 0.7, 1e-7) && close(corrected[1], 0.3, 1e-7);
    });
    s.check("mitigation inverts the forward model (2 qubits, tensor)", () => {
      const { corrected } = mitigateReadout(applyReadoutError([0.5, 0, 0, 0.5], 2, 0.05), 2, 0.05);
      return close(corrected[0], 0.5, 1e-6) && close(corrected[3], 0.5, 1e-6) && close(corrected[1], 0, 1e-6);
    });
  }

  // ── Classical shadows (seeded estimates) ───────────────────────────
  s.group("Classical shadows (Bell estimates)");
  {
    const bellC = circ(2, [gate("h", [0]), gate("cx", [1], [0])]);
    const sh = buildClassicalShadows(bellC, {}, [], 6000, mulberry32(7));
    s.check("shadows build for a 2-qubit state", () => sh !== null);
    s.check("estimated ⟨ZZ⟩ ≈ +1", () => sh !== null && Math.abs(estimatePauli(sh, "ZZ")! - 1) < 0.25);
    s.check("estimated ⟨XX⟩ ≈ +1", () => sh !== null && Math.abs(estimatePauli(sh, "XX")! - 1) < 0.25);
    s.check("estimated ⟨YY⟩ ≈ −1", () => sh !== null && Math.abs(estimatePauli(sh, "YY")! + 1) < 0.25);
  }

  // ── SWAP router (satisfies the coupling map) ───────────────────────
  s.group("SWAP router");
  {
    const line3 = [[1], [0, 2], [1]]; // adjacency list for a 0–1–2 line
    s.check("a distance-2 CX is routed with a SWAP", () =>
      routeCircuit(circ(3, [gate("cx", [2], [0])]), line3).swapsInserted >= 1);
    s.check("a routed circuit has zero connectivity violations", () => {
      const c = circ(3, [gate("cx", [1], [0], [], 0), gate("cx", [2], [1], [], 1), gate("cx", [2], [0], [], 2)]);
      return countConnectivityViolations(routeCircuit(c, line3).circuit, line3) === 0;
    });
  }

  // ── AI agent tools (the dispatcher the chat's agent mode drives) ───
  s.group("AI agent tools");
  {
    const makeCtx = (c: Circuit) => {
      let cur = c;
      const ctx: AgentContext = { getCircuit: () => cur, customGates: [], paramValues: {}, applyCircuit: (n) => { cur = n; }, addPlot: () => {} };
      return { ctx, get: () => cur };
    };
    const bellC = circ(2, [gate("h", [0]), gate("cx", [1], [0])]);
    s.check("get_resources reports CX=1 on a Bell circuit", () => executeTool("get_resources", {}, makeCtx(bellC).ctx).includes("CX=1"));
    s.check("expectation ⟨ZZ⟩ = 1 on a Bell state", () => executeTool("expectation", { observable: "ZZ" }, makeCtx(bellC).ctx).includes("1.0000"));
    s.check("get_analysis magic = 0 on a Clifford state", () => executeTool("get_analysis", { metric: "magic" }, makeCtx(bellC).ctx).includes("M₂ = 0.0000"));
    s.check("place_gate appends a gate via applyCircuit", () => {
      const m = makeCtx(circ(1, []));
      executeTool("place_gate", { gate: "h", targets: [0] }, m.ctx);
      return m.get().gates.length === 1 && m.get().gates[0].gateId === "h";
    });
    s.check("set_circuit_qasm rebuilds the circuit from QASM", () => {
      const m = makeCtx(circ(1, []));
      executeTool("set_circuit_qasm", { qasm: "OPENQASM 3;\nqubit[2] q;\nh q[0];\ncx q[0], q[1];\n" }, m.ctx);
      return m.get().numQubits === 2 && m.get().gates.length === 2;
    });
    s.check("an unknown tool name throws", () => {
      try { executeTool("nope", {}, makeCtx(bellC).ctx); return false; } catch { return true; }
    });
  }

  let passed = 0, failed = 0;
  for (const g of s.groups) for (const c of g.checks) (c.passed ? passed++ : failed++);
  const t1 = (typeof performance !== "undefined" ? performance.now() : Date.now());
  return { groups: s.groups, passed, failed, total: passed + failed, durationMs: t1 - t0 };
}
